# Generated by Django 4.1.7 on 2023-03-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0003_word_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word_check',
            new_name='NewWord',
        ),
    ]
